#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"

# install haproxy
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get install -y haproxy=2.4.\*

# give access
sudo cat<<EOF > /etc/sudoers.d/dokku-haproxy
%dokku ALL=(ALL) NOPASSWD:/etc/init.d/haproxy start, /etc/init.d/haproxy reload
EOF

chmod 0440 /etc/sudoers.d/dokku-haproxy

# set new haproxy config location
mkdir -p /var/lib/dokku-haproxy
touch /var/lib/dokku-haproxy/haproxy.cfg
sudo sed -i 's/#CONFIG=\"\/etc\/haproxy\/haproxy.cfg\"/CONFIG=\"\/var\/lib\/dokku-haproxy\/haproxy.cfg\"/g' /etc/default/haproxy

# give access
chown dokku:dokku /var/lib/dokku-haproxy
chown dokku:dokku /var/lib/dokku-haproxy/*

case "$DOKKU_DISTRO" in
  ubuntu)
    sudo /etc/init.d/haproxy start
    ;;
esac

haproxy_reload
