#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/haproxy/functions"

haproxy_proxy_enable() {
  declare desc="build haproxy config to proxy app containers from command line"
  local trigger="haproxy_proxy_enable"
  local APP="$1" ACTION="$2"

  if [[ "$(plugn trigger proxy-type "$APP")" == "haproxy" ]]; then
    haproxy_build_config "$APP"
    haproxy_reload
  fi
}

haproxy_proxy_enable "$@"
